Update azure-deploy.yml

diff --git a/.github/workflows/azure-deploy.yml b/.github/workflows/azure-deploy.yml
--- a/.github/workflows/azure-deploy.yml
+++ b/.github/workflows/azure-deploy.yml
@@ -39,8 +39,16 @@ jobs:
         with:
           name: dotnet-app
           path: ./publish
-
-
+      - name: Check Publish Profile
+  shell: bash
+  run: |
+    if [ -z "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" ]; then
+      echo "ERROR: AZURE_WEBAPP_PUBLISH_PROFILE is missing"
+      exit 1
+    else
+      echo "Publish profile secret is configured"
+    fi  
+      
   deploy:
     runs-on: ubuntu-latest
     needs: build
